language: node_js
node_js:
- "8"
sudo: false
addons:
  apt:
    sources:
     - sourceline: 'ppa:ubuntu-wine/ppa'
    packages:
     - wine
script:
  - bash ./deploy-to-gh-pages.sh
env:
  global:
    - GITHUB_REPO: "TheBrokenRail/Scratch3Builder"
    - secure: "ccolRM+GDbwF4bnxQ2JdVF5tmc5Jq/P1L9H1qx5cv0Ap8M7YVt5+qxilgHWCUCT7/o5bAibpIfgsFoHBxpdGWTCAiQBvGf22wQbtLlP058+Qu5Azrfkdkssa6qTj1zxbldeoh1TXk7B/pIHpzIF+pa7gM00yiUSviIhQJEGYZu8DgYzOEfltUU/iSwx5CC+VBBDiurNW1qGzwumuFvJ9QkKC51WygTdOwqVDxP8xHal7sYns5KzlEj2adGJbwopgd5qj+WS2mPaM6BjaRtup0C4GEqp0fMz/sK0msFCOdk1V+JNb8AZx5Etc4fdxuCg8Wvjc/e3LwyjeEeLC2QyLoPUq7RK5+bVJyIj07N/TpbhbukWR2j2f546DAYONjP5IouaEr17O5B0ifPEPtdChOsdTDJn/IR1TzFlqvvukkRElWUGBtaWuEjANA2KuWdHzqN7Gv0LWHoYtff2jK8YtmDfzCtvinJt1/AMiKNhmKzZ0ALg6ZNyhV9KJeNmzz5tQ4lkQSTn+sa486T6BiVHXnrlw84n39o1KH2PmTLwiVwUZI3j32Mcyn4Onnw5UOArj8DqDxY8sT05DTV1/PNBVx6yoCgshI7Cqj29Mjh1sXi9cOTXwevnAZi9oTxB1grM9diM4sFrhe6Nz1JeNqT2jEeYTY15iH0TxfmvcDuouWZM="
install:
- npm install
- npm update
